### ISSUE TITLE
contract violation when comparing snip% objects using equal?

### ISSUE THREAD

**Issue by alex-hhh** [racket/gui#119]
When the following program is run in DrRacket 7.1:

```racket
#lang racket
(require racket/gui pict pict/snip)
(define snip1 (make-object image-snip% (pict->bitmap (text "hello"))))
(define snip2 (make-object pict-snip% (text "hello")))
```

Trying to compare `snip1` and `snip2` using `equal?` I get a contract violation when trying to compare the two snips, but only if the `pict-snip%` is the first argument:

```
> (equal? snip1 snip2)
#f
> (equal? snip2 snip1)
. . other-equal-to?: contract violation
  expected: (is-a?/c image-snip%)
  given: (object:pict-snip% ...)
  in: the 1st argument of
      the other-equal-to? method in
      image-snip%/c
  contract from: 
      <pkgs>/snip-lib/racket/snip.rkt
  contract on: image-snip%
  blaming: E:\Alex\t\snip.rkt
   (assuming the contract is correct)
  at: <pkgs>/snip-lib/racket/snip.rkt:26.19
> 
```

**Comment by rfindler** [comment]
This appears to be a check in `image-snip%` that is intentional, but I'm not sure it should be.

**Comment by samth** [comment]
I think "equal? doesn't error" is an invariant we expect to hold, and therefore this check is wrong.

**Comment by alex-hhh** [comment]
I am not sure that the contract on the `other-equal-to?` method is wrong.  The `equal?` mechanism works fine if the `image-snip%` is compared against a string, for example:

```
> (equal? snip1 "hello")
#f
> (equal? "hello" snip1)
#f
> 
```

I suspect that the code that calls `other-equal-to?` is incorrect, but I am not familiar enough with the implementation.

**Comment by rmculpepper** [comment]
@alex-hhh `equal?` only calls user-defined implementations for structs (specified via `prop:equal+hash-code`) if the two struct instances have the same extension. That is, they have a common struct type with the `prop:equal+hash-code` property, and neither of them have a more specific struct type that redeclares that property. For classes, that translates to classes declaring that they implement the `equal<%>` interface. The bug is that the `snip%` class declares it implements the `equal<%>` interface and `image-snip%` just extends `snip%`, so its `other-equal-to` method should only assume it gets a `snip%`, not specifically a `image-snip%`.

I think just changing `image-snip%` to list `equal<%>` as an interface should fix this bug.

@samth `equal?` can error because it forces a delayed contract:

    (equal? (contract (vectorof number?) (vector 'bad 2 3) 'pos 'neg)
            (vector 1 2 3))

I agree it shouldn't error in this case, though.

**Comment by rfindler** [comment]
@rmculpepper but this change would not make the program return `#t`?

**Comment by rmculpepper** [comment]
No, it would make `equal?` enforce that an image-snip can only possibly be equal to another image-snip (without running any of the `equal-to?` etc methods). So both orders would produce `#f`.

**Comment by rfindler** [comment]
Just that change alone seems to affect the teaching languages in a bad way. This program (in BSL via the DrRacket language menu) seems to start returning two `#false`s, intead of two `#true`s, like it should (where "<put image here>" is replaced by an image inserted via Insert|Insert Image...).

```
(require 2htdp/image)
(define i <put image here>)
(equal? (rotate 0 i) i)
(equal? i (rotate 0 i))
```

**Comment by alex-hhh** [comment]
Hi There!  Could this issue be re-visited?   I just hit this bug again when trying to use `member` to look for a snip in a list of snips....  Thanks, Alex.

**Comment by alex-hhh** [comment]
I created a pull request to address this issue, https://github.com/racket/snip/pull/6, it handles correctly both my initial example and the BSL example that @rfindler provided.

**Comment by alex-hhh** [comment]
Hi @samth, it looks like the test for the snip equality is failing on master even after the pull request in the snip package was merged.   I suspect this is because the updated snip library is not used when the gui package is built?  I am not sure how to fix this problem, apart for disabling the test.  Do you have any suggestions?

**Comment by samth** [comment]
Almost certainly the problem is that the most recent snapshot when that ran didn't have the updated `snip` library. I re-ran it now; if that doesn't work we basically just have to wait till the new snapshot runs tonight.

**Comment by alex-hhh** [comment]
I verified that this is fixed in the snapshot build from 27 Nov 2019 (v7.5.0.8, win32 x86_64)
