### ISSUE TITLE
Visibility issue with name-message in GTK dark theme

### ISSUE THREAD

**Issue by aidalgol** [racket/gui#121]
(Started from racket/drracket#235.)

The `name-message` widget does not colour text any differently when running under GTK with a dark GTK theme set.

```racket
#lang racket/gui

(require mrlib/name-message)

(let* ((frame (new frame%
                   [label "Dark GTK bug"]
                   [width 320]
                   [height 240]))
       (message (new message%
                     [parent frame]
                     [label "Message"]))
       (button (new button%
                    [parent frame]
                    [label "Button"]))
       (name-msg (new name-message%
                      [parent frame]
                      [label "Name Message"])))
  (send frame show #t))
```
![racket-mrlib-new-message-demo](https://user-images.githubusercontent.com/2313201/52044916-26f78580-25a8-11e9-8853-7bde8c294daa.png)

It looks like the color-theming of more primitive widgets (such as `message` and `button`) are handled by wx (or the native toolkit), while mrlib draws the label text itself, and it is not checking to see whether the native toolkit is using a dark theme.

**Comment by rfindler** [comment]
I'm not sure how to tell if GTK is in dark-theme mode, but if someone were to figure that out and add some support to `racket/gui`, it would not be difficult to fix everything else to look at it and do the right thing.

**Comment by aidalgol** [comment]
The ideal way to handle this would be to query wxWidgets, which would in turn query the native toolkit (in this case, GTK), for whether a dark theme is in use, or for the theme name.  Unfortunately, there is no such mechanism in wx, and adding this to wx would need to be done in a way that the wx interface makes sense for every platform (as with everything in wx), which is well beyond my abilities.

From what I have found, even applications using GTK directly use heuristics comparing the foreground and background colors to determine whether they are running in dark mode, rather than looking for the substring "dark" in the theme name, or the value of the [`gtk-application-prefer-dark-theme`](https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-application-prefer-dark-theme) property.  (Looking at the theme name fails for dark themes that do not have "dark" in the name, and the "prefer dark theme" flag being set will have no effect if no dark themes are available on the system.)
## Examples of this issue in other projects
* [Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1461538)
* [Liferea](https://lzone.de/blog/Detecting%20a%20Dark%20Theme%20in%20GTK)

If I had experience with native GUI development on macOS, Windows, and GTK3, I would try solving this in wxWidgets itself, but as I do not, I suggest we implement a similar detection to that used by [Liferea](https://lzone.de/blog/Detecting%20a%20Dark%20Theme%20in%20GTK).

**Comment by mflatt** [comment]
Commit 71a6f0f42e130e8b91588dc5204d3c7e68e21804 is intended to help.

It seems to work right with Unix/Gtk and Mac OS (except that it doesn't change dynamically; I'm not sure why, since every call to one of the new functions goes through the `NSColor` class).

While Windows also has a dark-mode option, it's currently for UWP programs and not specified for Win32. (There are apparently undocumented ways to partially enable dark mode, as in https://stackoverflow.com/questions/53501268/win10-dark-theme-how-to-use-in-winapi )

**Comment by aidalgol** [comment]
@rfindler, I see that you started work on making use of this while I was screwing around with my Racket development setup, so I will leave you to it unless you get stuck, dragged away, or for whatever other reason need someone else to take over.

**Comment by rfindler** [comment]
Sounds good, thanks! I may bug you to let me know how it looks to you (via a snapshot), if that's okay @aidalgol ?

**Comment by rfindler** [comment]
I've pushed changes that hopefully work for some of the things and, assuming all goes well tonight, be available for tomorrow's nightly build (looks like about 11am Chicago time is when they finished last time, at least for the northwestern build). I'd love to hear how it looks to people.

**Comment by rfindler** [comment]
Shall we close the issue(s) or are there more places to fix?

Thanks,
Robby

**Comment by aidalgol** [comment]
I haven't noticed any other issues, so I'm happy for this to be closed as fixed.

**Comment by sorawee** [comment]
Fixed. Closing the issue.
