### ISSUE TITLE
event% get-time-stamp inconsistent across platforms

### ISSUE THREAD

**Issue by alex-hhh** [racket/gui#132]
The documentation for the `get-time-stamp` method of the `event%` class states that it:

> Returns the time, in milliseconds, when the event occurred. This time is compatible with times reported by Racket’s current-milliseconds procedure.

Unfortunately, this is not what happens for `mouse-event%` instances, and the behavior is inconsistent across platforms:

* on Windows, the timestamp is always 0, see https://github.com/racket/gui/blob/7ba65379eb2b6184bd1d12fdd03ad9c12a57928b/gui-lib/mred/private/wx/win32/window.rkt#L680
* on Linux, it is copied from the time member of one of `GdkEventMotion`, `GdkEventCrossing` or `GdkEventButton`, but it is unclear from the GTK documentation [1] what is the reference time for this member.  See https://github.com/racket/gui/blob/001c57b86c624ad367354d6bf168f55f82e79c20/gui-lib/mred/private/wx/gtk/window.rkt#L489
* on MacOS, it is copied from the `timestamp` member of the original `event`, which seems to be the time in seconds since system startup [2], see https://github.com/racket/gui/blob/03d6ac569cf619797edb40c8e4c2801d9ffe9b1a/gui-lib/mred/private/wx/cocoa/window.rkt#L485

[1] https://developer.gnome.org/gdk3/stable/gdk3-Event-Structures.html#GdkEventCrossing
[2] https://developer.apple.com/documentation/appkit/nsevent/1528239-timestamp

----

My preferred solution would be to make `get-times-stamp` do what the documentation specifies, as this would allow a Racket program to determine how old an event it by comparing it against `current-milliseconds`, however, it would be also an improvement to just update the Windows case to use an actual timestamp and update the documentation to specify that the epoch is unknown and the value can only be used for comparing two timestamps...

**Comment by evdubs** [comment]
What's wrong with having it be:
`[time-stamp (current-milliseconds)]`

**Comment by alex-hhh** [comment]
Using `current-milliseconds` is the simplest fix, making it consistent with the documentation and across platforms, but there are a few problems with using `current-milliseconds`:

* The mouse events are actually created inside the OS system libraries and they might be already a few milliseconds old when they reach the Racket code.  The MacOS and Linux libraries already supply a timestamp with these events, and this timestamp is already transferred to the `mouse-event%`, it is just that the timestamp is relative to the start time of the system. Windows does not appear to supply timestamps, but the best place to collect such a timestamp would be in the `WndProc` function, before the Racket code runs.
* the time returned by `current-milliseconds` can go backwards, as most systems these days adjust their clock from time servers -- the adjustments will usually be small, though, so it might not matter.
* I am not sure what the resolution of the `current-milliseconds` time is, On Windows platforms it uses `GetSystemTimeAsFileTime` and on all other platforms `gettimeofday`.  At least `GetSystemTimeAsFileTime` can have a resolution between 1 and 15 milliseconds, although this might be sufficient. Also, I am not sure what the resolution of the Linux and MacOS timers are.

**Comment by alex-hhh** [comment]
Fixed in https://github.com/racket/gui/commit/4c801f917a0e2a8c04eaab1b14278fd18b956e9f, see also https://github.com/racket/racket/issues/3626
