### ISSUE TITLE
xkbcommon error on requiring

### ISSUE THREAD

**Issue by andreyorst** [racket/gui#143]
I'm using GNU/Linux, with a GNOME Shell through Wayland as my desktop environment. My <kbd>Caps Lock</kbd> key is mapped to <kbd>Ctrl</kbd>, and <kbd>Ctrl</kbd> is mapped to <kbd>Win</kbd> key, because there's no <kbd>Win</kbd> key on my keyboard. I did it in the GNOME Tweaks program that provides convenient interface for additional keyboard layout settings:
![image](https://user-images.githubusercontent.com/19470159/63701438-9d522280-c82d-11e9-977d-59a018c93cd0.png)
![image](https://user-images.githubusercontent.com/19470159/63701466-ac38d500-c82d-11e9-84bf-1498e39319f1.png)

Whenever I start the REPL and `(require racket/gui)` I see this message:

```
$ racket
Welcome to Racket v7.0.
> (require racket/gui)
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Control, ignoring Lock
> 
```

If I disable caps lock related settings the message disappears. Should I care about this error, and does it affect the usage of the REPL in any way?

**Comment by andreyorst** [comment]
Actually, I've just noticed that changing the settings for caps lock to `Disabled` and enabling `Caps Lock as Ctrl` in the **Ctrl** menu fixes the issue, while still making it possible to use `Ctrl` as `Win` and `Caps` as `Ctrl`.

Though I don't think that the error should happen for original case

**Comment by soegaard** [comment]
The Wayland projet uses Xkbcommon.
The output is generated from:
https://github.com/xkbcommon/libxkbcommon/blob/master/src/xkbcomp/symbols.c#L463

So this message is not Racket related. There might be a log level you can set in order not to see the warning/error message.
