### ISSUE TITLE
MacOS Catalina breaks arrow keys in file dialogs

### ISSUE THREAD

**Issue by jbclements** [racket/gui#155]
It appears to me that under Catalina, arrow keys in the Mac file dialog don't work at all.

Steps to reproduce:

1) Start DrRacket (release candidate or 7.4, both behave the same).
2) Hit CMD-O (open file)
3) click once on a file in a directory with more than one file. (don't open, just select)
4) hit the up and down arrow keys, hear beep rather than seeing highlighted file change.

**Comment by jbclements** [comment]
Sadly, it appears that the shiny new entitled version of DrRacket has the same problem.

**Comment by sorawee** [comment]
I would hope that this will get fixed for Racket 7.7, so I tried debugging it. I tracked down the error to the following code:

```
#lang racket/base
(require ffi/unsafe/objc
         mred/private/wx/cocoa/utils
         mred/private/wx/cocoa/types
         mred/private/wx/cocoa/queue
         mred/private/wx/cocoa/frame)

(import-class NSSavePanel)
(promote-to-gui!)
(force-global-flush-resume)
(define ns (as-objc-allocation-with-retain
            (tell NSSavePanel savePanel)))
(tell #:type _NSInteger ns runModal)
(release ns)
```

This code creates the save dialog where the arrow key doesn't work.

I do not know what `force-global-flush-resume` (exported by `mred/private/wx/cocoa/frame`) does, but commenting it out doesn't seem to have any visible effect.

```
#lang racket/base
(require ffi/unsafe/objc
         mred/private/wx/cocoa/utils
         mred/private/wx/cocoa/types
         mred/private/wx/cocoa/queue
         mred/private/wx/cocoa/frame)

(import-class NSSavePanel)
(promote-to-gui!)
#;(force-global-flush-resume)
(define ns (as-objc-allocation-with-retain
            (tell NSSavePanel savePanel)))
(tell #:type _NSInteger ns runModal)
(release ns)
```

But now, comment out the import of `mred/private/wx/cocoa/frame`. The arrow key now works.

```
#lang racket/base
(require ffi/unsafe/objc
         mred/private/wx/cocoa/utils
         mred/private/wx/cocoa/types
         mred/private/wx/cocoa/queue
         #;mred/private/wx/cocoa/frame)

(import-class NSSavePanel)
(promote-to-gui!)
#;(force-global-flush-resume)
(define ns (as-objc-allocation-with-retain
            (tell NSSavePanel savePanel)))
(tell #:type _NSInteger ns runModal)
(release ns)
```

So it looks like some side-effect from importing `mred/private/wx/cocoa/frame` is the culprit.

**Comment by sorawee** [comment]
Note: this is running from the command-line. The first version somehow works fine in DrRacket, so does the program @jbclements gave above:

```
#lang racket

(require racket/gui/base)

(get-file)

(get-file)
```

**Comment by sorawee** [comment]
the side-effect of `mred/private/wx/cocoa/frame` is in turn due to the side-effect of `mred/private/wx/cocoa/menu-bar`.

```
#lang racket/base
(require ffi/unsafe/objc
         mred/private/wx/cocoa/utils
         mred/private/wx/cocoa/types
         mred/private/wx/cocoa/queue
         mred/private/wx/cocoa/const)

(import-class NSApplication NSMenu)

(define the-apple-menu #f)
(define recurring-for-command (make-parameter #f))

(define-objc-class RacketBarMenu NSMenu
  []
  ;; Disable automatic handling of keyboard shortcuts, except for
  ;;  the Apple menu
  (-a _BOOL (performKeyEquivalent: [_id evt])
      (or (and the-apple-menu
               (tell #:type _BOOL the-apple-menu performKeyEquivalent: evt))
          ;; Explicity send the event to the keyWindow:
          (and
           ;; Don't go into an infinite loop:
           (not (recurring-for-command))
           ;; Don't handle Cmd-` for cycling through windows:
           ;; [Is this right for all locales?]
           (not (equal? "`" (tell #:type _NSString evt characters)))
           ;; Otherwise, try to dispatch to the first respnder:
           (let ([w (tell app keyWindow)])
             (and w
                  (let ([r (tell w firstResponder)])
                    (and r
                         (begin
                           (parameterize ([recurring-for-command #t])
                             (let ([evt-type (tell #:type _NSInteger evt type)])
                               (cond
                                [(= NSKeyDown evt-type)
                                 (tell r keyDown: evt)]
                                [(= NSKeyUp evt-type)
                                 (tell r keyUp: evt)])))
                           #t)))))))))

(define cocoa-mb (tell (tell RacketBarMenu alloc) init))
(define app (tell NSApplication sharedApplication))
(tellv app setMainMenu: cocoa-mb)

(import-class NSSavePanel)
(promote-to-gui!)
(define ns (as-objc-allocation-with-retain
            (tell NSSavePanel savePanel)))
(tell #:type _NSInteger ns runModal)
```

The above program has the arrow keys problem. One of the following fixes the problem:

1. Comment out `(tellv app setMainMenu: cocoa-mb)`.
2. Comment out the ";; Disable automatic handling of keyboard shortcuts, except for ;;  the Apple menu" code (`(-a _BOOL (performKeyEquivalent: [_id evt]) ...)`)

**Comment by jbclements** [comment]
SO happy to see you working on this. This is a terrible inconenience.

Beyond the above, I've repeatedly now managed to get DrRacket into a state where no keys work in the save dialog at all; specifically, you can't even type a name for the saved file; you have to just click "save" to save the file as "Untitled.rkt" and then quit and restart DrR to get things reset.

Actually, @sorawee , I should have asked: have you tried to duplicate the additional problem I mentioned on December 13?

**Comment by sorawee** [comment]
I cannot get "Type cmd-g to open the "Go To the Folder" modal overlay." to work on step 4, with or without the fix. So a better way is probably to ask you to try the following code:

```
#lang racket

(require racket/gui/base
         ffi/unsafe/objc)

(import-class NSApplication NSMenu)

(define-objc-class EmptyBarMenu NSMenu [])
(define empty-mb (tell (tell EmptyBarMenu alloc) init))
(define app (tell NSApplication sharedApplication))
(define original-mb (tell app mainMenu))

(define (my-get-file)
  (dynamic-wind
    (thunk (tellv app setMainMenu: empty-mb))
    (thunk (get-file))
    (thunk (tellv app setMainMenu: original-mb))))

(my-get-file)
(my-get-file)
```

**Comment by jbclements** [comment]
Silly me. Should have written <cmd>-<shift>-g, not <cmd>-g. Sigh. 

But, the reveal: yes! This solves the bug. I would *love* to see this in 7.7

**Comment by sorawee** [comment]
I do not know any internal invariant of the code, so I am not comfortable submitting a PR. The two people who touched https://github.com/racket/gui/blob/master/gui-lib/mred/private/wx/cocoa/menu-bar.rkt are @mflatt and @samth, so I would wait for them to get an opportunity to fix it.

**Comment by samth** [comment]
Actually, my commit here was only moving files around; @mflatt is the only person who's worked on this code.

**Comment by jbclements** [comment]
Many, many thanks for fixing this.
