### ISSUE TITLE
With auto-parens, " or | near strings or comments is not correctly handled

### ISSUE THREAD

**Issue by bzyeung** [racket/gui#164]
With automatic parentheses on, when `"` or `|` are typed at the end of a line comment, a second character gets added.  However, as both characters are now part of the comment, the character isn't smart-skipped by typing it again.  In a related problem, when typing those characters at the beginning, "outside" the comment, they do *not* add the extra character.  These are both in contrast to the behavior with parens, so I think this qualifies as a bug.

Given that I've just been playing with similar code in the same area while working on new feature #162, I'm happy to take a swing at this, unless this behavior is actually intended.

**Comment by rfindler** [comment]
Sounds like a bug to me, yes. Thanks!
