### ISSUE TITLE
Automatic double-quote insertion broken

### ISSUE THREAD

**Issue by jbclements** [racket/gui#171]
In the current git master, it appears that insertion of double-quotes is broken when inserting
double-quotes before other double-quotes.

How to reproduce:
1) Start DrRacket, select the "Automatic Parentheses & Quotes" option in editing>general.
2) Open a new buffer
3) hit return three times, type a double-quote. See two double-quotes inserted, as expected.
4) hit the up arrow twice. Type a double quote. See only *one* double-quote inserted, and 
syntax highlighting become angry red.

I believe this error does not affect the v7.6 release.

**Comment by jbclements** [comment]
@bzyeung , can you take a look at this? I see a regression related to double-quotes before an existing string, and I'm guessing it's related to your recent commit?

**Comment by bzyeung** [comment]
Yes, that's my fault.  The check for whether the character was "in a string or comment" was occurring after the first character was added.

**Comment by jbclements** [comment]
Thanks!
