### ISSUE TITLE
Spell checking doesn't react to a region becoming a non-string/text token

### ISSUE THREAD

**Issue by gfbee** [racket/gui#182]
Caveat: my install of aspell is broken, so this was tested by mocking the aspell module, but was expected because the implementation in `color.rkt` looks like it would have this bug.

To reproduce, select the Edit menu item “Spell Check String Constants”, misspell a string `"ood"` and modify its token type without editing the string's characters. E.g. turn it into the symbol `'good` by editing around it, or turn it into an identifier, or comment it out, etc. Asking to skip to next misspelled word, or getting the suggestions, still considers the original characters to be a misspelled word.

**Comment by samth** [comment]
I can reproduce this behavior.

**Comment by rfindler** [comment]
I don't doubt this is a bug. I haven't had a chance to look into it but fixing existing bugs sounds like a good way to get to know a codebase. :)

**Comment by gfbee** [comment]
I should have noted on closing that I was about to open the more general issue #183.

**Comment by gfbee** [comment]
@rfindler the implementation looks like it once did (try to?) do this properly, which would explain the excess nop logic in `add-coloring/spell` and the redirection of all coloring through it. Presumably at one time the regions with `suggestions` being `#f` were reset. If I consider tackling this, it would be worth knowing what caused you to remove that resetting (maybe just efficiency?) since that could inidicate that a fix is much more work than one might expect in advance.

**Comment by rfindler** [comment]
I don't know. But efficiency seems like a good thing to check into for sure!

**Comment by samth** [comment]
Maybe viewing the history of that file in git will tell you when it changed?

**Comment by gfbee** [comment]
Here's where Robby removed the code that reset the non-misspelled regions: https://github.com/racket/gui/commit/b0d5a8681eff7d8b04ecd1ba1c5b43b8183895b5?diff=split .
The `and` had an effect for both the `#f` and non-`#f` cases, which turned into a `when` that does nothing in the `#f` case.
My fix would simply put back in the `#f` case. But that undoes half of a patch for a “sometimes” problem, but I don't know how to test whether it still fixes that problem because I don't know what it was.

**Comment by rfindler** [comment]
Are you referring to the `and` that got removed on line 468?

**Comment by rfindler** [comment]
oh, no. I see what you mean.

I recall not being able to make a real test case for this but what would happen is that the spelling regions would get out of sync sometimes and spelling corrections would, on occasion, edit the wrong region in the editor.

**Comment by rfindler** [comment]
I'm not seeing why this would fix the reported bug. We get into that situation only when the token type is either `'string` or `'text` and the bug is when some region of text changes from being one of those to being some other type. Wouldn't a fix have to take the form of tokens that didn't have those types clearing out the `misspelled-regions` interval map?

**Comment by gfbee** [comment]
The coloring for all the token types goes through `add-coloring/spell`, see https://github.com/racket/gui/blob/b0d5a8681eff7d8b04ecd1ba1c5b43b8183895b5/gui-lib/framework/private/color.rkt#L454 .
That's something I found odd, for the same reason you thought it wasn't the case, and which I “cleaned up” in a recent (now withdrawn) pull request

**Comment by rfindler** [comment]
oh, yes. You're right. Thanks.

I think your change is a good one but I agree that it would make sense to run a timing test first. Here's one:

```
#lang racket
(require framework)

(define t (new racket:text%))
(send t load-file (collection-file-path "unit.rkt" "drracket" "private"))
(time (send t freeze-colorer))
```

**Comment by rfindler** [comment]
I think this fixed now (by https://github.com/racket/gui/pull/187), so I'll close it. Thanks for finding this problem and its fix!
