### ISSUE TITLE
[doc] on-lexer-valid says "Augments <method not found>"

### ISSUE THREAD

**Issue by sorawee** [racket/gui#185]
I think the title is clear enough. Here's a link to the doc: https://docs.racket-lang.org/framework/Color.html?q=classify-position#%28meth._%28%28%28lib._framework%2Fmain..rkt%29._color~3atext~3c~25~3e%29._on-lexer-valid%29%29

**Comment by spdegabrielle** [comment]
is this caused by the `any` parameter in `@defmethod` in line 373?

`@defmethod[#:mode augment (on-lexer-valid [valid? boolean?]) any]{`

https://github.com/racket/gui/blob/master/gui-doc/scribblings/framework/color.scrbl#L373

```
  @defmethod[#:mode augment (on-lexer-valid [valid? boolean?]) any]{
    This method is an observer for when the lexer is working.  It is called
    when the lexer's state changes from valid to invalid (and back).  The
    @racket[valid?] argument indicates if the lexer has finished running over
    the editor (or not).

    The default method just returns @racket[(void?)].
  }
```
renders as

![image](https://user-images.githubusercontent.com/108047/81808040-080bd100-9517-11ea-8c8c-b334822b9a93.png)

**Comment by sorawee** [comment]
Pretty sure it should be `#:mode pubment` instead.

**Comment by sorawee** [comment]
Here's a list of "Augments <method not found>" problems in other places:

- https://docs.racket-lang.org/tools/drracket_unit.html (4 issues)
- https://docs.racket-lang.org/tools/drracket_language.html (14 issues)
- https://docs.racket-lang.org/tools/drracket_rep.html (1 issue)
- https://docs.racket-lang.org/framework/Racket.html (1 issue)
- https://docs.racket-lang.org/framework/Frame.html (4 issues)

**Comment by spdegabrielle** [comment]
> Pretty sure it should be #:mode pubment instead.

Better to test it if you are unsure?

Steps: 

1. `raco pkg update --clone <PKG>`
2. fork the racket/<PKG> repo on GitHub
3. add your fork as a remote: `git remote add fork https://github.com/<YOUR-USERNAME>/<PKG>`
4. make a new branch, `git checkout -b my-edits`
5. do edits
6. rebuild documentation using `scribble colour.scrbl` or `raco pkg update gui`  
7. commit changes, `git commit`
8. push to the fork, `git push fork my-edits`
9. create a pull request.

https://blog.racket-lang.org/2017/09/tutorial-contributing-to-racket.html

**Comment by sorawee** [comment]
The above two commits/PRs should fix everything except the four issues on https://docs.racket-lang.org/tools/drracket_unit.html, which I still couldn't figure out what went wrong.

**Comment by sorawee** [comment]
@rfindler could you reopen the issue? There're still issues on https://docs.racket-lang.org/tools/drracket_unit.html and the pending PR for `racket/gui`. Thanks!

**Comment by rfindler** [comment]
Oh, sorry! I was just wanting to get your fixes.

And thank you, too!

**Comment by rfindler** [comment]
Sorry-- I pushed a commit that closed this issue but it isn't done.

**Comment by rfindler** [comment]
Forgot to mention it in the commit, but this fixes two more of them: https://github.com/racket/drracket/commit/15e3a9ac1225346a63a03747c722e9e1c27db820

**Comment by rfindler** [comment]
I think those two commits fix all the problems in drracket_unit.html.

**Comment by sorawee** [comment]
All fixed!
