### ISSUE TITLE
Call to set-padding on text% hangs

### ISSUE THREAD

**Issue by aymanosman** [racket/gui#192]
Minimal example

```
#lang racket/gui

(define frame
  (new frame% [label "my frame"] [width 400] [height 300]))

(define canvas (new editor-canvas% [parent frame]))
(define text (new text%))

(send canvas set-editor text) ;; won't hang if this is called below

(send text auto-wrap #t)
(send text set-padding 10 10 10 10) ;; hangs here

;; (send canvas set-editor text) ;; won't hang if this is called here

(send frame show #t)
```

Tried on Racket 7.6 and 7.7 [3m].

**Comment by alex-hhh** [comment]
I can confirm that this is happening for me too.  I think the problem is that the `editor-canvas%` has zero dimensions until the frame is shown, and the call to `set-padding` is somehow affected by that.  Adding a call to `reflow-container` after the canvas is created also "fixes" the problem:

```
(send frame reflow-container)
```
