### ISSUE TITLE
GtkBuilder

### ISSUE THREAD

**Issue by WEREWOLFGHOST** [racket/gui#194]
Why there is no GtkBuilder implementation in gui-lib so that we can use Glade to build GUI more quickly?

**Comment by spdegabrielle** [comment]
Racket does have a gui builder: MrEd-Designer by @Metaxal -> 
https://github.com/Metaxal/MrEd-Designer
see https://github.com/Metaxal/MrEd-Designer/wiki for some screenshots

**Comment by spdegabrielle** [comment]
@WEREWOLFGHOST please close this issue if it has been resolved.
