### ISSUE TITLE
DrRacket CS 7.8 fails to open a 2nd file from Windows Explorer

### ISSUE THREAD

**Issue by Friendseeker** [racket/gui#200]
The issue is very similar to:
https://github.com/racket/gui/issues/139

Except for the fact that instead of a crash, nothing happens after double-clicking the .rkt file.

Excepted Behavior:
DrRacket should open a new tab corresponding to the file I double-clicked.

Windows Version: Windows 10 2004
DrRacket Version: CS 7.8

Additional Information that might be of your interest:
This issue is not cross-platform, I failed to reproduce the issue on Mac OS.

**Comment by bmitc** [comment]
I have this issue as well on Windows 10 and Racket CS 7.9.

**Comment by formalizm** [comment]
The issue is still present in 8.2.

**Comment by default-kramer** [comment]
The root cause is most likely https://github.com/racket/gui/issues/245

**Comment by pacopepepipo** [comment]
same problem here, was trying to follow the edx course and it's a pain to follow it with all the rkts

**Comment by formalizm** [comment]
The issue is fixed in Racket 8.3, see details in the duplicate racket/drracket#456 and the root cause #245.
