### ISSUE TITLE
framework/preferences does not account for prefix that gets added on write to disk.

### ISSUE THREAD

**Issue by kurinoku** [racket/gui#208]
I already rewrote the code I was working on, but if I'm not mistaken the issue goes as follows,

1. I replaced the low level read and write procedures
2. When it starts without a file `set-default` and `set` do not complain about anything
3. Restart application set will complain that `plt:framework:my-pref` (I don't remember the prefix exactly but was something like that) symbol does not have a default value.

I am sure I call `set-default` before either `get` or `set`.
I'm only 80% sure that it's not my fault, although I think I misunderstood something along the way.

**Comment by rfindler** [comment]
Do you have a small fragment of code that illustrates the issue?

Robby

**Comment by kurinoku** [comment]
well it appears it was my fault somehow, i'm going guerrilla so this project isnt using git, and the small example i made seems to be working as it's expected, so my bad...

**Comment by kurinoku** [comment]
I think now it's completely my responsability to handle the prefix, but I don't understand how I'm supposed to know the prefix the loader uses.
https://gist.github.com/kurinoku/b7679bff4c9b9a6cde6cdc72147d815f

**Comment by rfindler** [comment]
You should not need to be aware of the prefix. My guess is you are "mixing
levels" using both the file/ module and the framework/ module for accessing
the prefs. If that's right, the short answer is "don't do that".

Robby
