### ISSUE TITLE
Could you please add some contributing guidelines?

### ISSUE THREAD

**Issue by Lazerbeak12345** [racket/gui#210]
Hi!

I, awhile ago, was working on a pull request for this repo. - don't worry about that anymore, that's been resolved by others. (thanks, and great work too!)

It was _remarkably_ difficult to set up an environment such that I could test the changes I was making to this library. This isn't really about debugging, though, as some calls to `print`, once I got the environment set up, was more than satisfactory.

The problem is: **There don't seem to be any instructions for how to set up the development environment for this project on a computer.**

I'd love to continue helping out on this project when I have the time, but unfortunately, most of my time that I spent on that pr was actually fixing a broken environment without any guide, and not therefore as productive (or even helpful) as I had hoped it would be. **Please add a guideline somewhere in this repo, standard conventions being in `CONTRIBUTING.md` or in the readme, that includes instructions on how to contribute on Windows, Unix and Mac.** Thanks!

**Comment by samth** [comment]
While it might be good to add this to the README of all of the repositories that make up the Racket distribution, you can see extensive contributing guidelines here: https://github.com/racket/racket/blob/master/build.md linked from https://github.com/racket/racket/blob/master/.github/CONTRIBUTING.md
