### ISSUE TITLE
text% erase after tabify causes error output?

### ISSUE THREAD

**Issue by jbclements** [racket/gui#220]
This behavior seems new since a few weeks ago; calling "erase" on a text% after calling "tabify-all" can produce error text, though strangely it doesn't halt evaluation.  I'm running on git HEAD, using macOS Big Sur on a 2015 Macbook Pro.

Here's a program that illustrates this behavior:

```
#lang racket

(require framework
         racket/gui)


(define f (new frame% [label ""]))
(define indenting-text (new racket:text%))
(define ec (new editor-canvas%
                [parent f]
                [editor indenting-text]))

(send indenting-text erase)
(send indenting-text insert "((\n))" 0)
(send indenting-text tabify-all)
(send indenting-text erase)
(printf "still alive\n")
```

running this (command-line is fine) produces this text:

```
still alive
open-input-text-editor: starting index is out of range
  starting index: 2
  valid range: [0, 0]
  editor: (object:set-mode-mixin ...)
  context...:
   /Users/clements/racket/racket/share/pkgs/gui-lib/framework/private/color.rkt:333:4: re-tokenize-move-to-next-ls method in text-mixin
   /Users/clements/racket/racket/share/pkgs/gui-lib/framework/private/color.rkt:592:4: colorer-driver method in text-mixin
   /Users/clements/racket/racket/share/pkgs/gui-lib/framework/private/color.rkt:615:4: colorer-callback method in text-mixin
   /Users/clements/racket/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:435:6
   /Users/clements/racket/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:486:32
   /Users/clements/racket/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:634:3
pajaro2:/tmp clements> 
```

The printf illustrates that even though it's the second call to "erase" that's triggering the error text, evaluation continues. I'm confused!

**Comment by rfindler** [comment]
This is the syntax colorer. When a change happens to the buffer, it updates internal data structures (apparently in a bogus way) that causes it to do coloring, but that coloring happens on a future event callback. Not that it is especially relevant for this bug, but `freeze-colorer` is the method that causes all of the pending coloring work to happen. I don't know if it is the same bug or not, but it is the same code as [this issue](https://github.com/racket/drracket/issues/458).

**Comment by jbclements** [comment]
Okay, I'll close this one. I'll also add a note to that one pointing out that for a workaround, it appears that you can manually call "freeze-colorer". Thanks!
