### ISSUE TITLE
the `weak?` option of `color-prefs:register-color-scheme-entry-change-callback` is broken

### ISSUE THREAD

**Issue by yjqww6** [racket/gui#224]
In the following example, the `f` won't be called unless the weak option is not used.
```racket
#lang racket
(require framework racket/draw)

(define (f _) 
  (displayln "called"))

(color-prefs:register-color-scheme-entry-change-callback
 'framework:basic-canvas-background
 f
 #t)
(collect-garbage)
(color-prefs:set-in-color-scheme
 'framework:basic-canvas-background
 (make-object color% 255 255 255))
```
It looks like the procedure passed would be contracted, and holding such a value weakly doesn't make sense.

`canvas:color-mixin` seems ok because it uses the internal uncontracted version of `color-prefs:register-color-scheme-entry-change-callback`.

**Comment by rfindler** [comment]
Thanks!
