### ISSUE TITLE
Scrolls too fast with 2-finger scrolling on laptop

### ISSUE THREAD

**Issue by samth** [racket/gui#23]
With the new `racket/gui` scrolling, things scroll very fast on my laptop when using 2-finger scrolling on the touchpad (much faster than in Chrome or Firefox on the same laptop, or with the mouse wheel in DrRacket on a different machine).

**Comment by mflatt** [comment]
@samth Has this problem been fixed for you by Will's patch?

**Comment by samth** [comment]
Yes, this is now fixed.
