### ISSUE TITLE
DrRacket popup menus broken on KDE Wayland

### ISSUE THREAD

**Issue by LiberalArtist** [racket/gui#259]
Using the 8.3.900 release candidate on a KDE Wayland session, DrRacket's file and definitions popup menu buttons (i.e. the first two described [here](https://docs.racket-lang.org/drracket/buttons.html)) close immediately after clicking on them. More specifically, the seem to close on mouse up: I can get them to stay open by holding down the mouse button, but I can't interact with their contents, and they close when I release the mouse button. I've put a screen capture below.

If I start DrRacket from the terminal, this message is logged when I click on the menu/button:
```
(drracket:30924): Gtk-WARNING **: 16:44:46.432: no trigger event for menu popup
```
I presume this is a problem with the framework component, not something specific to DrRacket, but I don't know what component implements those buttons/menus.

The behavior is new since the 8.3 release, which draws those buttons/menus quite differently: that's in the non-animated screenshot below.

I am seeing this with Kubuntu 21.10, KDE Plasma 5.23.5, KDE Frameworks 5.90.0, and Qt 5.15.2. It happens in all of the various ways I've tried starting and building DrRacket, including the download from the pre-release site.

![drracket-8 3 900-kde-wayland](https://user-images.githubusercontent.com/10700996/150658765-5c9fdbb7-310a-4114-b454-ff4afce15a0c.gif)

![Screenshot_20220122_184221](https://user-images.githubusercontent.com/10700996/150659030-35a3b3c4-c6e2-47df-b56b-71c78912f528.png)

**Comment by mflatt** [comment]
An attempt at a repair is now in the Utah snapshot (not pre-release) build: https://www.cs.utah.edu/plt/snapshots/. Does it behave any better on your machine?

**Comment by LiberalArtist** [comment]
I've been using it since yesterday, and it seems to be working well—thanks!

**Comment by mflatt** [comment]
@LiberalArtist Thanks for trying it out! I'll close the issue for now.
