### ISSUE TITLE
Selecting a Directory

### ISSUE THREAD

**Issue by atstp** [racket/gui#262]
I'm looking for a way to support directory selection. `finder:get-file` is pretty close but seems limited to files.

Is there a good alternative? Is it possible to use `finder:get-file` for this?

**Comment by sorawee** [comment]
If I understand correctly, you can use [`get-directory`](https://docs.racket-lang.org/gui/Windowing_Functions.html#%28def._%28%28lib._mred%2Fmain..rkt%29._get-directory%29%29). It is implemented with platform-independent dialog box. This is different from the `finder:` variant, which could show platform-dependent dialog box. But it should be a good workaround for now.

**Comment by atstp** [comment]
Looks like `get-directory` will do the trick. Thanks!
