### ISSUE TITLE
Tabs in `tab-panel%` flicker badly in Racket 8.5 on Windows

### ISSUE THREAD

**Issue by alex-hhh** [racket/gui#273]
The tabs in the `tab-panel%` flicker a lot when the mouse is hovering over them.  Also, when dragging the tabs, they flicker so badly that it is not possible to read the tab names any more.  This happens in Racket 8.5, but not 8.4, the two videos below show the difference.

Also, this is not DrRacket specific, I use `tab-panel%` in my own application and they have same behavior

https://user-images.githubusercontent.com/11592690/171646074-27a694ea-b9c8-4546-ba4b-53b2fa19130d.mp4

https://user-images.githubusercontent.com/11592690/171646090-86907baa-37cf-4a50-a83f-adf505d899ff.mp4

**Comment by spdegabrielle** [comment]
FWIW I’m getting this on windows too.

**Comment by mflatt** [comment]
I revised refresh for transparent canvases on Windows (as used internally by `tab-panel%`). Does the latest snapshot at https://www.cs.utah.edu/plt/snapshots/ behave any better?

**Comment by alex-hhh** [comment]
I installed version 8.5.0.8--2022-06-08 and the tabs no longer flicker.  I think this issue can be closed now.  Thanks for looking into it.
