### ISSUE TITLE
~/.XCompose characters are detected but not printed with xim

### ISSUE THREAD

**Issue by jsmaniac** [racket/gui#29]
I have `~/.XCompose` mappings for <kbd>Compose</kbd> <kbd>g</kbd> <kbd>l</kbd> → `λ` and <kbd>Compose</kbd> <kbd>&lt;</kbd> <kbd>-</kbd> <kbd>-</kbd> <kbd>&gt;</kbd> → `↔`, among others.

When I start `drracket` or `gracket` with `GTK_IM_MODULE="xim"` and `XMODIFIERS="@im=none"`, the compose sequences are correctly detected but the character is not printed. For example:

* If I type <kbd>Compose</kbd> <kbd>g</kbd> <kbd>l</kbd> <kbd>a</kbd> <kbd>b</kbd> <kbd>c</kbd>, I get `abc` instead of `λabc`
* If I type <kbd>Compose</kbd> <kbd>&lt;</kbd> <kbd>-</kbd> <kbd>-</kbd> <kbd>&gt;</kbd> <kbd>a</kbd> <kbd>b</kbd> <kbd>c</kbd>, I get `abc` instead of `↔abc` (but I don't get `>abc`, so it recognized the four-key compose sequence).

I get the same problem with `GTK_IM_MODULE="xim"` and `XMODIFIERS="@im=local"`. Both this and the `@im=none` settings work perfectly if I run `gedit`, for example.

I tested this on a fresh up-to-date ubuntu 14.04.4 installation, it works with racket 5.0 `racket-5.0-bin-x86_64-linux-f7.sh`, but not with 5.3 `racket-5.3.6-bin-x86_64-linux-debian-squeeze.sh`, nor with `6.1.1`, `6.3` and `6.4.0.13`. Although I'm sure I had my compose key working with `xim` on `6.3.x` nightly builds back in October to December 2015, but I might have used `PLT_GTK2="y"` or some other combination of environment variables.

If needed, ask and I can upload a virtual machine reproducing the problem.

```
$ racket --version
Welcome to Racket v6.4.0.13.

$ env | grep '\(IM_MODULE\|XMODIFIERS\)'
CLUTTER_IM_MODULE=xim
QT_IM_MODULE=xim
XMODIFIERS=@im=none
QT4_IM_MODULE=xim
GTK_IM_MODULE=xim

$ cat ~/.XCompose
…
<Multi_key> <less> <minus> <greater>    : "↔"   U2194           # LEFT RIGHT ARROW (kragen's)
…
<Multi_key> <g> <l>             : "λ" U03BB     # GREEK SMALL LETTER LAMBDA (GREEK SMALL LETTER LAMDA)
…
```

**Comment by mflatt** [comment]
I think the linked commit will fix the problem for the next build. There's some danger that I've broken keyboard input in some other context, but everything I tried still works.

**Comment by jsmaniac** [comment]
This seems to be fixed in the latest version, both UIM and XIM work fine for me, so I'm closing this. Thanks @mflatt !
