### ISSUE TITLE
DrRacket 8.11 "import from" tooltip flickers

### ISSUE THREAD

**Issue by shhyou** [racket/gui#320]
- Version:
  - Racket 8.11.0.3 [cs]
  - `gui-lib`: racket/gui@a4f3070aeb8fe986d
  - `drracket: racket/drracket@2c9c89446fe672e21
- Description: the "import from ..." tool tip flickers when the mouse moves over it
- OS: Mac
- Screen recording: https://github.com/racket/gui/assets/1910898/177c7c37-9865-41c6-94ba-317cb7ddc547

**Comment by rfindler** [comment]
This flickering shouldn't happen because the tooltip isn't supposed to overlap the identifier. I can't seem to get the tooltip to overlap the `list` on my machine. I tried fiddling with the size of the window and the font size but couldn't get them to overlap.

**Comment by shhyou** [comment]
Indeed, I cannot get the tool tip to overlay `list` anymore. I don't know how that happened in the first place. The binding arrow in the screen recording also pointed to the left of `list` which is strange.
