### ISSUE TITLE
macOS: text field misrendering

### ISSUE THREAD

**Issue by Bogdanp** [racket/gui#325]
I've tested this using a fresh build of Racket HEAD on macOS 14.4 (arm64) and on the `release` branch. The following program

```racket
#lang racket/gui

(define frame
  (new frame%
       [label "Test"]))

(define msg
  (new message%
       [label "test"]
       [parent frame]))

(define input
  (new text-field%
       [label "test"]
       [parent frame]))

(send frame show #t)
```

renders as

<img width="247" alt="Screenshot 2024-04-25 at 07 42 38" src="https://github.com/racket/gui/assets/43347/9ae2f38a-561f-42f0-b23d-6087d947d434">

The background of the text field seems to extend past its boundary and cover other widgets. The problem is worse in more complex apps:

<img width="832" alt="Screenshot 2024-04-25 at 07 44 57" src="https://github.com/racket/gui/assets/43347/740f6730-e4be-435e-823c-e6bd80ab0549">

<img width="964" alt="Screenshot 2024-04-25 at 07 46 27" src="https://github.com/racket/gui/assets/43347/f0f62c8c-92d1-4386-a496-3b7d3a057c1f">

When I try a [recent snapshot build](https://users.cs.utah.edu/plt/snapshots/2024-04-23-7844684fb3/index.html), the bug doesn't happen, so the issue might be with some recent change to racket itself, since there haven't been recent commits here, though I haven't been able to pinpoint the commit.

**Comment by sorawee** [comment]
See also:

- https://github.com/racket/drracket/issues/670
- https://github.com/racket/drracket/issues/652

I have been experiencing this for four months now, and thought it's something wrong with my computer, since no one else appeared to encounter it.

**Comment by Bogdanp** [comment]
In that case it seems that building from source is the common link?

**Comment by alex-hhh** [comment]
Someone reported a similar issue in ActivityLog2, using Racket 8.11.1: https://github.com/alex-hhh/ActivityLog2/issues/97

Unfortunately, I'm not using MacOS, and have no way of verifying this...

**Comment by Bogdanp** [comment]
I've narrowed the problem a little further. It seems to be an issue with the `control-border` style on `canvas%`:

```racket
#lang racket/gui

(define frame
  (new frame%
       [label "Test"]))

(define p
  (new panel%
       [parent frame]
       [style '(border)]
       [vert-margin 10]
       [horiz-margin 10]))

(define c
  (new canvas%
       [parent p]
       [style '(control-border)]))

(send frame show #t)

```

<img width="534" alt="Screenshot 2024-04-25 at 08 58 50" src="https://github.com/racket/gui/assets/43347/a0b454c7-3fa4-4c75-8909-4b57c95dba63">
