### ISSUE TITLE
reindent-paragraph incorrect behaviour with long lines

### ISSUE THREAD

**Issue by jsmaniac** [racket/gui#39]
In the following code, the line `bbbb…` is two caracters longer than the maximum line length for `reindent-paragraph`. It is preceded by a shorter line `aa`.

```
#lang scribble/base

aa
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
Hello world lorem ipsum hello world lorem ipsum hi world
lorem ipsum hello world lorem ipsum hi world lorem ipsum
hello world lorem ipsum hello world lorem ipsum hello…
```

When pressing <kbd>Alt</kbd>+<kbd>Q</kbd>, the third line is appended to the `bbbb…` one, which results in a line way longer than the maximum:

```
#lang scribble/base

aa
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb Hello world lorem ipsum hello world lorem ipsum hi world
lorem ipsum hello world lorem ipsum hi world lorem ipsum
hello world lorem ipsum hello world lorem ipsum hello…
```

 If <kbd>Alt</kbd>+<kbd>Q</kbd> is pressed again, the following line is appended, and so on. The `reindent-paragraph` should instead leave `bbbb…` alone on its line (in my case it was a long `@hyperlink` causing this behaviour).

Tested with Racket 6.6.0.3.

**Comment by rfindler** [comment]
This was fixed by this commit: https://github.com/racket/gui/commit/0ae0a5b8044faecb49cc10b58f423f8548fade0f
