### ISSUE TITLE
Alt-Q reflow ignores closing braces on the last line

### ISSUE THREAD

**Issue by jsmaniac** [racket/gui#42]
With the default paragraph width of 60, the line should be broken (it's 64 characters long), but Alt+Q has no effect..

```
#lang scribble/manual
@emph{
 @emph{
  @emph{
   @emph{
    @emph{
     blah blah blah blah blah blah blah blah blah blah blah}}}}}
```

**Comment by rfindler** [comment]
What version are you using?

**Comment by jsmaniac** [comment]
Racket v.6.6.0.4, I just re-tested right now with the latest nightly (20160823-471f371).

My apologies, the bug report contained a typo: "With the default paragraph width of 65…", I meant 60, not 65.

**Comment by rfindler** [comment]
Oh, I see: the problem happens only when the insertion point is in the `}`s somewhere. When it is in the `blah` portion, it gets reflowed to this:

```
#lang scribble/manual
@emph{ @emph{ @emph{ @emph{ @emph{ blah blah blah blah blah
     blah blah blah blah blah blah}}}}}
```
