### ISSUE TITLE
Slider number incorrect for large values (on OS X at least)

### ISSUE THREAD

**Issue by LeifAndersen** [racket/gui#51]
Consider the following code that draw a single window with a slider:

```
#lang racket/base

(require racket/gui/base
         racket/class)

(define frame
  (new frame% [label ""]))
(define slider
  (new slider%
       [parent frame]
       [label ""]
       [min-value 0]
       [max-value 5001]))
(send frame show #t)
(send slider set-value 3000)
```

Here the slider is set to 3000, with a max value of 5001. However, when the slider is actually drawn, it show up with only the number 300:

<img width="201" alt="screen shot 2016-10-22 at 2 07 25 pm 1" src="https://cloud.githubusercontent.com/assets/285926/19621480/e711c4de-9860-11e6-8b67-aea39afd9c3b.png">

However, if you move it up, even a little bit, it jumps up to 3001, but every few numbers (that tend to end in `0`, the number gets truncated in.

**Comment by LeifAndersen** [comment]
Also, I should point out that this issue does seem to show up in any stable version of Racket.

**Comment by LeifAndersen** [comment]
Also also, this bug does not show up on linux (including both stable and heads).

**Comment by LeifAndersen** [comment]
I've got it. The problem is that the label width is based on the max value. Which makes sense for integers that are at a fixed width font, but for variable width font integers this does not make sense.

For example, if the max value is
11111

And I set the slider to the number
10101

Even though the first is bigger, the second one is drawn taking more space:

11111
10101

**Comment by LeifAndersen** [comment]
PR #52 handles this.

**Comment by rfindler** [comment]
It is clipping the number drawing incorrectly?
