### ISSUE TITLE
infinite loop on `replace-all` in drracket

### ISSUE THREAD

**Issue by stchang** [racket/gui#60]
Found another issue while testing #59 (but unrelated to #59).

DrRacket goes into inf loop:
1) start with empty buffer except for "#lang racket"
2) press run
3) with focus on interactions window, open search box, enter "a" as search term
4) choose Edit -> Replace All
5) inf loop

Investigating now.

**Comment by rfindler** [comment]
Starting drracket via "racket -l drracket" (or just via the shell script),
the getting into the infinite loop and hitting control-c (in the shell) may
get you a helpful stack trace.
