### ISSUE TITLE
combo-field% odd behavior

### ISSUE THREAD

**Issue by lehitoskin** [racket/gui#65]
I have a combo-field and according to the docs if you send it `append`, it will append the label-string to the list of choices, however...

```
> (send dc-combo append "foo")
(object:menu-item% ...)
```

It neither returns `(void)` nor does it appear to append anything to the choices list. In fact, I can't seem to get it working on just about any level. I click on the field and an ellipsis appears instead of a list of items available. See the attached screenshots for an illustration. I can't tell if the return value is a bug in the code or a bug in the docs, but clicking on the field and seeing only an ellipsis certainly seems like a bug in the racket/gui code to me.

![2016-12-20-211350_600x313_scrot](https://cloud.githubusercontent.com/assets/2506703/21378212/935f15fe-c6f9-11e6-8f6a-9560d6adb328.png)
![2016-12-20-211419_601x295_scrot](https://cloud.githubusercontent.com/assets/2506703/21378213/95e9a834-c6f9-11e6-8e1d-ea9c83371263.png)

Here's the relevant code:
```racket
(define meta-frame
  (new frame%
       [label "Metadata"]
       [width 600]
       [height 500]))

(define dc-combo
  (new combo-field%
       [parent meta-frame]
       [label "Dublin Core"]
       [choices (list "dc:subject" "dc:creator")]
       [init-value "dc:subject"]
       [callback (λ (combo evt)
                   (displayln (send evt get-event-type)))]))
```

P.S. I'm running Racket v6.7 on amd64 Gentoo

**Comment by sjmackenzie** [comment]
I have this exact problem too

``` racket
#lang racket/gui

(define frame
  (new frame%
       [label "Example"]
       [width 500]	 
       [height 50]))

(define combo-field
  (new combo-field%
       (label "Combo")
       (parent frame)
       (choices (list "Field" "test" "test2"))
       (init-value "Field")))
 
(send frame show #t)
```

racket 6.12
OS: nixos, using this patch that gets gtk3 working https://github.com/NixOS/nixpkgs/pull/41557/files

![combo-field-popup](https://user-images.githubusercontent.com/158321/41040933-5f9a83b8-69d0-11e8-99a1-0530a08eaa97.png)

![combo-field-popup-fail](https://user-images.githubusercontent.com/158321/41040938-63826298-69d0-11e8-8bda-6e4fa21bcbff.png)

**Comment by mflatt** [comment]
Does 0f4f8d0d2d97e82d4a57b1cd778c40926c520269 fix this problem?

That patch is included in snapshot builds available at https://pre.racket-lang.org

**Comment by SnapCracklePopGone** [comment]
Can confirm that the pre-racket build did fix this issue for me.  I clearly observed the same behavior as documented in this issue with Racket v7.2 on Fedora Linux 25.  Problem went away after installing the recommended pre-release on the same system.

**Comment by lehitoskin** [comment]
@mflatt That patch fixed my issue. Thank you.

**Comment by Rscho314** [comment]
I still get the exact same issue on Racket 7.3, Debian Linux x64, XCFE 4. Did the pre-release patch no make it into Racket 7.3?
If that's not the case, will it be into  7.4?

Thanks!

**Comment by mflatt** [comment]
You are correct: the repair did not make it into v7.3, even though it was meant to be included, due to a mistake on my part. It's definitely in v7.4. The initial build for v7.4 is now available at http://pre-release.racket-lang.org/, and I've double-checked to make sure the repair is there.
