### ISSUE TITLE
get-text-from-user with disallow-invalid still allows submission by pressing Enter

### ISSUE THREAD

**Issue by adhameer** [racket/gui#76]
When `'disallow-invalid` is included in the style passed to `get-text-from-user` and a `validate` predicate is provided, the Ok button in the resulting dialog is grayed out whenever `validate` returns `#f` on the user input. However, the user can still submit their input by pressing Enter. Is this the intended behaviour? It would be nice if submission by pressing Enter could also be disabled when the Ok button is grayed out, so that extra error checking is not needed.

Example:

```racket
(define maybe-zero (get-text-from-user
                    "Title" "Label" #f "" '(disallow-invalid)
                    #:validate (λ (x) (equal? x "0"))))
; maybe-zero could be something other than "0" here if the user pressed Enter ...
```

**Comment by mflatt** [comment]
That's a bug, and I'll push a repair.

Thanks for the report!
